// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PainelRotinaEstudos.Data;

#nullable disable

namespace PainelRotinaEstudos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106143425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PainelRotinaEstudos.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 6, 11, 34, 21, 399, DateTimeKind.Local).AddTicks(7345),
                            Day = "SEG",
                            Description = "Matemática Algebra Linear",
                            Subject = "MAT23",
                            Time = "3:30"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 6, 11, 34, 21, 399, DateTimeKind.Local).AddTicks(7348),
                            Day = "SEG",
                            Description = "Programação Desenvolvimento Web",
                            Subject = "PDR15a",
                            Time = "PDR15a"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 6, 11, 34, 21, 399, DateTimeKind.Local).AddTicks(7350),
                            Day = "TER",
                            Description = "Fisica Mecânica",
                            Subject = "FIS101",
                            Time = "2:00"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 6, 11, 34, 21, 399, DateTimeKind.Local).AddTicks(7352),
                            Day = "QUA",
                            Description = "Engenharia de Software",
                            Subject = "ENG204",
                            Time = "4:15"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 6, 11, 34, 21, 399, DateTimeKind.Local).AddTicks(7355),
                            Day = "QUI",
                            Description = "Algoritmos Avançados",
                            Subject = "ALG301",
                            Time = "1:30"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 6, 11, 34, 21, 399, DateTimeKind.Local).AddTicks(7357),
                            Day = "SEX",
                            Description = "Banco de Dados",
                            Subject = "BD202",
                            Time = "3:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
